[package]
name = "water-levels-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
water-levels-core = { path = "../core" }
anyhow = "1.0.51"
wasm-bindgen = "0.2.78"
console_error_panic_hook = "0.1.7"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
